project:
  type: website
  output-dir: docs
  
website:
  title: "Marie Tolteca"
  favicon: images/Marie Tolteca-1.png
  navbar:
    title: false
    logo: images/Marie Tolteca-1.png
    logo-alt: the name marie tolteca with a wiener dog on top of the name
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - icon: github
        href: https://github.com/marietolteca00/marietolteca00.github.io #how to change
      - blog_post.qmd
  page-footer:
    left: Copyright 2025, Marie Tolteca
    right:
      - href: https://github.com/marietolteca00
        icon: github

format:
  html:
    theme: 
      - morph
      - 
    toc: true
    page-layout: full
    mainfont: Josefin Sans


